"""Nueva db.

Revision ID: 9ca8bae60bfd
Revises: 
Create Date: 2022-09-08 20:12:58.915545

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ca8bae60bfd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('country',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dniType',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sex',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('userType',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('province',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('idContry', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['idContry'], ['country.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('location',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('idProvince', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['idProvince'], ['province.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('person',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('idTypeDni', sa.Integer(), nullable=True),
    sa.Column('dni', sa.Integer(), nullable=True),
    sa.Column('address', sa.String(length=100), nullable=True),
    sa.Column('idLocation', sa.Integer(), nullable=True),
    sa.Column('idCountry', sa.Integer(), nullable=True),
    sa.Column('born', sa.TIMESTAMP(), nullable=True),
    sa.Column('idSex', sa.Integer(), nullable=True),
    sa.Column('phone', sa.Integer(), nullable=False),
    sa.Column('mail', sa.String(length=50), nullable=False),
    sa.Column('uploadDate', sa.TIMESTAMP(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['idCountry'], ['country.id'], ),
    sa.ForeignKeyConstraint(['idLocation'], ['location.id'], ),
    sa.ForeignKeyConstraint(['idSex'], ['sex.id'], ),
    sa.ForeignKeyConstraint(['idTypeDni'], ['dniType.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('password', sa.String(length=100), nullable=True),
    sa.Column('idUserType', sa.Integer(), nullable=True),
    sa.Column('fCarga', sa.TIMESTAMP(), nullable=True),
    sa.Column('idPerson', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['idPerson'], ['person.id'], ),
    sa.ForeignKeyConstraint(['idUserType'], ['userType.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('person')
    op.drop_table('location')
    op.drop_table('province')
    op.drop_table('userType')
    op.drop_table('sex')
    op.drop_table('dniType')
    op.drop_table('country')
    # ### end Alembic commands ###
